apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
data:
  APP_ENV: {{ .Values.config.appEnv | quote }}
  APP_MESSAGE: {{ .Values.config.appMessage | quote }}